### ISSUE TITLE
no wx with Schc Pop of 10

### ISSUE THREAD

**Issue by wxmanted** [wxstall/GridsSimp#11]
Seems that schc pops only gets triggered at values greater than 10.  Did a pop rounder, which set pop to 10 and pot to 10, and Wx didn't get created for it. 

Probably should set wx creation at values greater than 9.5, not 10 so that a forecaster that sees 10 on their screen gets a wx grid there.   Likewise, better check to see if regular wx gets created at  values greater than 14.5 not 15.

**Comment by wxstall** [comment]
Fix attempted, still testing

**Comment by wxstall** [comment]
Fixed for 0.1.3
