### ISSUE TITLE
Loading elements

### ISSUE THREAD

**Issue by wxmanted** [wxstall/GridsSimp#15]
When starting GridsSimp it will load foundation grids:

T, Td, MaxT, MinT, Sky, Wind, WindGust, Visibility, Wx, PoP, PoP12, QPF, SnowAmt, StormTotalSnow, SnowLevel, IceAccum, Hazards

On step 2 it loads the PoT grids as you have them...

After the completion of Step 3 (end of GridsSimp) it loads the Public Weather Element Group.  If Aviation was selected at the beginning it loads the Aviation Element Group.

**Comment by wxmanted** [comment]
If aviation is selected at the beginning we probably would add all the following foundation aviation elements:
LLWS, LLWSHgt, CloudBasePrimary, CloudBaseSecondary, CloudBaseConditional, Ceiling, and VisibilityConditional...in addition to all the grids above.

(You can worry about this stuff later...)

**Comment by wxstall** [comment]
Partial completion for 0.1.3. 
Aviation elements have been merged with open DAS ticket https://github.com/wxstall/GridsSimp/issues/9

Latest update will load grids properly at each step and load the Restore database with Fcst database grids during step 2.
