### ISSUE TITLE
Loading edited parms back in 

### ISSUE THREAD

**Issue by wxmanted** [wxstall/GridsSimp#17]
In the PoT step any edited elements need to be loaded back into the Grid manager so the forecaster can view them.

I attempted to fix this myself in the GS utility, but was skittish with you gone.   We'll need to fix it for real - by doing a for loop of the elements inside the gridschanged variable

Made edits to GS utility  near lines 950 1280 and 1350.

**Comment by wxstall** [comment]
Fixed for 0.1.4
