### ISSUE TITLE
MaxT MinT issue

### ISSUE THREAD

**Issue by wxmanted** [wxstall/GridsSimp#24]
See email for more info.  

Run consistency check on MinT and Max to ensure Max isn't lower than Min.  And Min isn't lower than max before running the diurnal procedure for T.   

Perhaps a message to the forecaster should be displayed that asks which grid should be fixed or at least highlighting that changes are being made to a particular grid because of this issue.

**Comment by wxstall** [comment]
Hotfix implemented to patch 0.1.3 to fix this. Gave MinT priority, it will adjust MaxT accordingly.
